# Change these first
owner: 8-Magic # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: 8-Magic
    url: https://8.alialmasi.ir
    icon: https://8.alialmasi.ir/logo.svg
  - name: 8-Magic API
    url: https://api.8.alialmasi.ir
    icon: https://api.8.alialmasi.ir/logo.svg

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://api.8.alialmasi.ir/logo.svg
  name: 8-Magic Status
  theme: dark
  introTitle: "🎱 8-Magic Status Dashboard ✨"
  introMessage: "Welcome to the official 8-Magic status page, powered by GitHub and Upptime. Here, you'll find real-time updates on system performance, outages, and planned maintenance."
  navbar:
    - title: 8-Magic
      href: https://8.alialmasi.ir
    - title: 8-Magic API
      href: https://api.8.alialmasi.ir
    - title: GitHub
      href: https://github.com/8-Magic

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
